import { PostsDataBase } from '../posts.inteface';

export const data: PostsDataBase[] = [
  {
    id: '1',
    alias: 'ivory',
    email: 'Ivory_Schaden@example.net',
    name: 'Ivory',
    lastName: 'Kerluke',
    deleted: false,
  },
  {
    id: '2',
    alias: 'angeline',
    email: 'Angeline_Ritchie52@example.org',
    name: 'Angeline',
    lastName: 'Emard',
    deleted: false,
  },
  {
    id: '3',
    alias: 'emmie',
    email: 'Emmie_Reilly@example.com',
    name: 'Emmie',
    lastName: "D'Amore",
    deleted: false,
  },
  {
    id: '4',
    alias: 'wilfred',
    email: 'Wilfred.Haley@example.org',
    name: 'Wilfred',
    lastName: 'Walker',
    deleted: false,
  },
  {
    id: '5',
    alias: 'chelsey',
    email: 'Chelsey_Wunsch9@example.net',
    name: 'Chelsey',
    lastName: 'Hills',
    deleted: false,
  },
  {
    id: '6',
    alias: 'mitchell',
    email: 'Mitchell_Beatty0@example.com',
    name: 'Mitchell',
    lastName: 'Jacobs',
    deleted: false,
  },
  {
    id: '7',
    alias: 'janiya',
    email: 'Janiya.McLaughlin@example.com',
    name: 'Janiya',
    lastName: 'Block',
    deleted: false,
  },
  {
    id: '8',
    alias: 'greg',
    email: 'Greg.White88@example.org',
    name: 'Greg',
    lastName: 'Satterfield',
    deleted: false,
  },
  {
    id: '9',
    alias: 'deven',
    email: 'Deven17@example.net',
    name: 'Deven',
    lastName: 'Hoeger',
    deleted: false,
  },
  {
    id: '10',
    alias: 'milo',
    email: 'Milo63@example.net',
    name: 'Milo',
    lastName: 'Graham',
    deleted: false,
  },
  {
    id: '11',
    alias: 'lafayette',
    email: 'Lafayette51@example.com',
    name: 'Lafayette',
    lastName: 'Greenfelder',
    deleted: false,
  },
  {
    id: '12',
    alias: 'montana',
    email: 'Montana10@example.org',
    name: 'Montana',
    lastName: 'Bogan',
    deleted: false,
  },
  {
    id: '13',
    alias: 'dana',
    email: 'Dana_Douglas@example.org',
    name: 'Dana',
    lastName: 'Kuhlman',
    deleted: false,
  },
  {
    id: '14',
    alias: 'yadira',
    email: 'Yadira80@example.org',
    name: 'Yadira',
    lastName: 'Altenwerth',
    deleted: false,
  },
  {
    id: '15',
    alias: 'roosevelt',
    email: 'Roosevelt.Ernser29@example.com',
    name: 'Roosevelt',
    lastName: 'Schumm',
    deleted: false,
  },
  {
    id: '16',
    alias: 'emmy',
    email: 'Emmy_Roob@example.net',
    name: 'Emmy',
    lastName: 'Harris',
    deleted: false,
  },
  {
    id: '17',
    alias: 'xavier',
    email: 'Xavier.Walker@example.net',
    name: 'Xavier',
    lastName: 'Mante',
    deleted: false,
  },
  {
    id: '18',
    alias: 'eloise',
    email: 'Eloise30@example.net',
    name: 'Eloise',
    lastName: 'Smitham',
    deleted: false,
  },
  {
    id: '19',
    alias: 'marianna',
    email: 'Marianna89@example.net',
    name: 'Marianna',
    lastName: 'Emmerich',
    deleted: false,
  },
  {
    id: '20',
    alias: 'erik',
    email: 'Erik_Gusikowski78@example.com',
    name: 'Erik',
    lastName: 'Beatty',
    deleted: false,
  },
  {
    id: '21',
    alias: 'rafaela',
    email: 'Rafaela.Lakin65@example.com',
    name: 'Rafaela',
    lastName: 'Auer',
    deleted: false,
  },
  {
    id: '22',
    alias: 'trever',
    email: 'Trever.Thompson74@example.org',
    name: 'Trever',
    lastName: 'Ledner',
    deleted: false,
  },
  {
    id: '23',
    alias: 'tom',
    email: 'Tom63@example.org',
    name: 'Tom',
    lastName: 'Monahan',
    deleted: false,
  },
  {
    id: '24',
    alias: 'chaya',
    email: 'Chaya.Wisozk@example.net',
    name: 'Chaya',
    lastName: 'Mosciski',
    deleted: false,
  },
  {
    id: '25',
    alias: 'alfonso',
    email: 'Alfonso92@example.net',
    name: 'Alfonso',
    lastName: 'Beahan',
    deleted: false,
  },
  {
    id: '26',
    alias: 'gaston',
    email: 'Gaston_Rolfson78@example.net',
    name: 'Gaston',
    lastName: 'Dibbert',
    deleted: false,
  },
  {
    id: '27',
    alias: 'liliana',
    email: 'Liliana.Kohler37@example.com',
    name: 'Liliana',
    lastName: 'Batz',
    deleted: false,
  },
  {
    id: '28',
    alias: 'lewis',
    email: 'Lewis15@example.com',
    name: 'Lewis',
    lastName: 'Johns',
    deleted: false,
  },
  {
    id: '29',
    alias: 'alda',
    email: 'Alda56@example.com',
    name: 'Alda',
    lastName: 'Walter',
    deleted: false,
  },
  {
    id: '30',
    alias: 'vella',
    email: 'Vella_Borer12@example.org',
    name: 'Vella',
    lastName: 'Feeney',
    deleted: false,
  },
  {
    id: '31',
    alias: 'brigitte',
    email: 'Brigitte7@example.com',
    name: 'Brigitte',
    lastName: 'Willms',
    deleted: false,
  },
  {
    id: '32',
    alias: 'jaeden',
    email: 'Jaeden_Smitham92@example.org',
    name: 'Jaeden',
    lastName: 'Bergstrom',
    deleted: false,
  },
  {
    id: '33',
    alias: 'earline',
    email: 'Earline50@example.net',
    name: 'Earline',
    lastName: 'Steuber',
    deleted: false,
  },
  {
    id: '34',
    alias: 'mitchell',
    email: 'Mitchell.Lockman16@example.net',
    name: 'Mitchell',
    lastName: 'Jacobi',
    deleted: false,
  },
  {
    id: '35',
    alias: 'eleonore',
    email: 'Eleonore52@example.com',
    name: 'Eleonore',
    lastName: 'Simonis',
    deleted: false,
  },
  {
    id: '36',
    alias: 'izabella',
    email: 'Izabella81@example.net',
    name: 'Izabella',
    lastName: 'Gorczany',
    deleted: false,
  },
  {
    id: '37',
    alias: 'sabryna',
    email: 'Sabryna_Walter@example.com',
    name: 'Sabryna',
    lastName: 'Keeling',
    deleted: false,
  },
  {
    id: '38',
    alias: 'zander',
    email: 'Zander.Erdman4@example.org',
    name: 'Zander',
    lastName: 'Cremin',
    deleted: false,
  },
  {
    id: '39',
    alias: 'bessie',
    email: 'Bessie_Wuckert97@example.net',
    name: 'Bessie',
    lastName: 'Streich',
    deleted: false,
  },
  {
    id: '40',
    alias: 'zula',
    email: 'Zula_MacGyver54@example.org',
    name: 'Zula',
    lastName: 'Torp',
    deleted: false,
  },
  {
    id: '41',
    alias: 'buddy',
    email: 'Buddy.OHara21@example.org',
    name: 'Buddy',
    lastName: 'Adams',
    deleted: false,
  },
  {
    id: '42',
    alias: 'eloy',
    email: 'Eloy.Parker55@example.com',
    name: 'Eloy',
    lastName: 'Purdy',
    deleted: false,
  },
  {
    id: '43',
    alias: 'aaron',
    email: 'Aaron.Ritchie@example.org',
    name: 'Aaron',
    lastName: "O'Keefe",
    deleted: false,
  },
  {
    id: '44',
    alias: 'jarod',
    email: 'Jarod.Jones88@example.com',
    name: 'Jarod',
    lastName: 'Herman',
    deleted: false,
  },
  {
    id: '45',
    alias: 'bettie',
    email: 'Bettie_Quigley68@example.net',
    name: 'Bettie',
    lastName: 'Murphy',
    deleted: false,
  },
  {
    id: '46',
    alias: 'sheridan',
    email: 'Sheridan96@example.org',
    name: 'Sheridan',
    lastName: 'Yost',
    deleted: false,
  },
  {
    id: '47',
    alias: 'barry',
    email: 'Barry91@example.com',
    name: 'Barry',
    lastName: 'Borer',
    deleted: false,
  },
  {
    id: '48',
    alias: 'enrique',
    email: 'Enrique.Schultz6@example.org',
    name: 'Enrique',
    lastName: 'Beier',
    deleted: false,
  },
  {
    id: '49',
    alias: 'dallas',
    email: 'Dallas_Cummings76@example.org',
    name: 'Dallas',
    lastName: 'Trantow',
    deleted: false,
  },
  {
    id: '50',
    alias: 'sheridan',
    email: 'Sheridan_Schumm96@example.com',
    name: 'Sheridan',
    lastName: 'Paucek',
    deleted: false,
  },
  {
    id: '51',
    alias: 'davin',
    email: 'Davin_MacGyver@example.com',
    name: 'Davin',
    lastName: 'Schroeder',
    deleted: false,
  },
  {
    id: '52',
    alias: 'lavern',
    email: 'Lavern_Hahn@example.org',
    name: 'Lavern',
    lastName: 'Predovic',
    deleted: false,
  },
  {
    id: '53',
    alias: 'preston',
    email: 'Preston_OKon13@example.net',
    name: 'Preston',
    lastName: 'Ruecker',
    deleted: false,
  },
  {
    id: '54',
    alias: 'orval',
    email: 'Orval_Padberg@example.org',
    name: 'Orval',
    lastName: 'Beer',
    deleted: false,
  },
  {
    id: '55',
    alias: 'karley',
    email: 'Karley66@example.com',
    name: 'Karley',
    lastName: 'Ruecker',
    deleted: false,
  },
  {
    id: '56',
    alias: 'harvey',
    email: 'Harvey.Wilkinson@example.org',
    name: 'Harvey',
    lastName: 'Schoen',
    deleted: false,
  },
  {
    id: '57',
    alias: 'jaleel',
    email: 'Jaleel43@example.net',
    name: 'Jaleel',
    lastName: 'Beier',
    deleted: false,
  },
  {
    id: '58',
    alias: 'mariano',
    email: 'Mariano.Boyle@example.org',
    name: 'Mariano',
    lastName: 'Wyman',
    deleted: false,
  },
  {
    id: '59',
    alias: 'wiley',
    email: 'Wiley.White@example.net',
    name: 'Wiley',
    lastName: 'Zboncak',
    deleted: false,
  },
  {
    id: '60',
    alias: 'laurie',
    email: 'Laurie_Lind@example.org',
    name: 'Laurie',
    lastName: 'Crona',
    deleted: false,
  },
  {
    id: '61',
    alias: 'keenan',
    email: 'Keenan.Stroman44@example.org',
    name: 'Keenan',
    lastName: 'Bauch',
    deleted: false,
  },
  {
    id: '62',
    alias: 'randal',
    email: 'Randal21@example.org',
    name: 'Randal',
    lastName: 'Beer',
    deleted: false,
  },
  {
    id: '63',
    alias: 'noelia',
    email: 'Noelia87@example.org',
    name: 'Noelia',
    lastName: 'Runolfsdottir',
    deleted: false,
  },
  {
    id: '64',
    alias: 'josiane',
    email: 'Josiane.Conroy61@example.org',
    name: 'Josiane',
    lastName: 'Harvey',
    deleted: false,
  },
  {
    id: '65',
    alias: 'winnifred',
    email: 'Winnifred77@example.org',
    name: 'Winnifred',
    lastName: 'Ward',
    deleted: false,
  },
  {
    id: '66',
    alias: 'ella',
    email: 'Ella_Littel5@example.com',
    name: 'Ella',
    lastName: 'Waters',
    deleted: false,
  },
  {
    id: '67',
    alias: 'elisha',
    email: 'Elisha.Smitham@example.org',
    name: 'Elisha',
    lastName: 'Kulas',
    deleted: false,
  },
  {
    id: '68',
    alias: 'jedediah',
    email: 'Jedediah_Mayer@example.net',
    name: 'Jedediah',
    lastName: 'Bailey',
    deleted: false,
  },
  {
    id: '69',
    alias: 'noel',
    email: 'Noel.Bailey38@example.com',
    name: 'Noel',
    lastName: 'Mayert',
    deleted: false,
  },
  {
    id: '70',
    alias: 'mafalda',
    email: 'Mafalda35@example.org',
    name: 'Mafalda',
    lastName: 'Beatty',
    deleted: false,
  },
  {
    id: '71',
    alias: 'norberto',
    email: 'Norberto_Schumm@example.com',
    name: 'Norberto',
    lastName: 'Schmidt',
    deleted: false,
  },
  {
    id: '72',
    alias: 'rosalia',
    email: 'Rosalia_Runte97@example.com',
    name: 'Rosalia',
    lastName: 'Rolfson',
    deleted: false,
  },
  {
    id: '73',
    alias: 'efren',
    email: 'Efren.Corkery@example.net',
    name: 'Efren',
    lastName: 'Friesen',
    deleted: false,
  },
  {
    id: '74',
    alias: 'eino',
    email: 'Eino73@example.com',
    name: 'Eino',
    lastName: 'Haag',
    deleted: false,
  },
  {
    id: '75',
    alias: 'dereck',
    email: 'Dereck7@example.net',
    name: 'Dereck',
    lastName: 'Schultz',
    deleted: false,
  },
  {
    id: '76',
    alias: 'major',
    email: 'Major_Stark12@example.org',
    name: 'Major',
    lastName: 'Weissnat',
    deleted: false,
  },
  {
    id: '77',
    alias: 'tavares',
    email: 'Tavares56@example.org',
    name: 'Tavares',
    lastName: 'Rolfson',
    deleted: false,
  },
  {
    id: '78',
    alias: 'gilbert',
    email: 'Gilbert.Beatty17@example.net',
    name: 'Gilbert',
    lastName: 'Beer',
    deleted: false,
  },
  {
    id: '79',
    alias: 'everette',
    email: 'Everette44@example.com',
    name: 'Everette',
    lastName: 'Fritsch',
    deleted: false,
  },
  {
    id: '80',
    alias: 'darrion',
    email: 'Darrion.Corkery@example.net',
    name: 'Darrion',
    lastName: 'Mayer',
    deleted: false,
  },
  {
    id: '81',
    alias: 'ramona',
    email: 'Ramona_Boehm@example.org',
    name: 'Ramona',
    lastName: 'Connelly',
    deleted: false,
  },
  {
    id: '82',
    alias: 'misty',
    email: 'Misty16@example.com',
    name: 'Misty',
    lastName: 'Graham',
    deleted: false,
  },
  {
    id: '83',
    alias: 'kailey',
    email: 'Kailey_Torp34@example.net',
    name: 'Kailey',
    lastName: 'Fisher',
    deleted: false,
  },
  {
    id: '84',
    alias: 'olaf',
    email: 'Olaf.Runolfsson@example.net',
    name: 'Olaf',
    lastName: 'Spencer',
    deleted: false,
  },
  {
    id: '85',
    alias: 'raheem',
    email: 'Raheem_Rempel36@example.com',
    name: 'Raheem',
    lastName: 'Reynolds',
    deleted: false,
  },
  {
    id: '86',
    alias: 'johathan',
    email: 'Johathan.Boehm@example.org',
    name: 'Johathan',
    lastName: 'Murphy',
    deleted: false,
  },
  {
    id: '87',
    alias: 'vance',
    email: 'Vance_Altenwerth@example.org',
    name: 'Vance',
    lastName: 'Ortiz',
    deleted: false,
  },
  {
    id: '88',
    alias: 'lincoln',
    email: 'Lincoln_Stark@example.org',
    name: 'Lincoln',
    lastName: 'Rolfson',
    deleted: false,
  },
  {
    id: '89',
    alias: 'stuart',
    email: 'Stuart.Padberg@example.com',
    name: 'Stuart',
    lastName: 'Gleichner',
    deleted: false,
  },
  {
    id: '90',
    alias: 'jack',
    email: 'Jack.Fay@example.org',
    name: 'Jack',
    lastName: 'Langosh',
    deleted: false,
  },
  {
    id: '91',
    alias: 'lorenzo',
    email: 'Lorenzo7@example.com',
    name: 'Lorenzo',
    lastName: 'Lesch',
    deleted: false,
  },
  {
    id: '92',
    alias: 'bethel',
    email: 'Bethel.Heller51@example.com',
    name: 'Bethel',
    lastName: 'Dare',
    deleted: false,
  },
  {
    id: '93',
    alias: 'carmel',
    email: 'Carmel.Ryan86@example.org',
    name: 'Carmel',
    lastName: 'Rodriguez',
    deleted: false,
  },
  {
    id: '94',
    alias: 'krystel',
    email: 'Krystel93@example.com',
    name: 'Krystel',
    lastName: 'Huel',
    deleted: false,
  },
  {
    id: '95',
    alias: 'remington',
    email: 'Remington56@example.org',
    name: 'Remington',
    lastName: 'Abbott',
    deleted: false,
  },
  {
    id: '96',
    alias: 'angus',
    email: 'Angus_DuBuque29@example.org',
    name: 'Angus',
    lastName: 'Weissnat',
    deleted: false,
  },
  {
    id: '97',
    alias: 'maddison',
    email: 'Maddison_Dooley@example.com',
    name: 'Maddison',
    lastName: 'Kertzmann',
    deleted: false,
  },
  {
    id: '98',
    alias: 'jessie',
    email: 'Jessie21@example.com',
    name: 'Jessie',
    lastName: 'Haag',
    deleted: false,
  },
  {
    id: '99',
    alias: 'yasmine',
    email: 'Yasmine_Nicolas59@example.org',
    name: 'Yasmine',
    lastName: 'Feil',
    deleted: false,
  },
  {
    id: '100',
    alias: 'lois',
    email: 'Lois_Kerluke35@example.org',
    name: 'Lois',
    lastName: 'Quigley',
    deleted: false,
  },
];
